Repository collab-community/coding-youtubers, pull requests merged in 2022-10, with the labels that each got.

#59 DSA content shifted from main README to DSA sub folder
  DSA/README.md
  README.md
Labels: size/S, Hacktoberfest, Hacktoberfest-accepted

#60 Web development resources segregated
  README.md
  Web Development/README.md
Labels: size/M, Hacktoberfest, Hacktoberfest-accepted

#58 Update README.md
  DSA/README.md
Labels: size/XS

#61 Update README.md
  README.md
Labels: size/XS

#65 Update DSA/README.md
  DSA/README.md
Labels: size/XS, Hacktoberfest, Hacktoberfest-accepted

#63 Update README.md
  AI/ML/README.md
Labels: size/XS

#67 All in one channels added
  All in One/README.md
Labels: good first issue, size/XS, Hacktoberfest, Hacktoberfest-accepted
