Repository collab-community/coding-youtubers, pull requests merged in 2022-08, with the labels that each got.

#1 Add YouTubers that helped me begin my coding Journey.
  README.md
Labels: size/XS

#6 Add Tech With Tim
  README.md
Labels: size/XS

#10 Removed grammatical errors and added description changes.
  README.md
Labels: size/S

#12 Update README.md
  README.md
Labels: size/S

#14 Minor change
  README.md
Labels: size/XS

#18 Grammar correction
  README.md
Labels: size/XS

#17 Added 4 YouTube channels
  README.md
Labels: size/XS

#23 Added Fireship & Bengali YouTubers.
  README.md
  _config.yml
Labels: size/S

#25 Update README.md
  README.md
Labels: size/S

#28 Categorized the YouTube Channels in README
  README.md
Labels: size/M

#35 Updated readme.md
  README.md
Labels: size/XS

#34 Updated with JavaScript Mastery channel
  README.md
Labels: size/XS

#36 table headers in bold
  assets/styles.css
  index.html
Labels: size/S

#38 Revert "table headers in bold"
  assets/styles.css
  index.html
Labels: size/S

#37 Created contributing.md file
  Assets/step3.png
  CONTRIBUTING.md
  README.md
Labels: size/M

#41 Add banner
  README.md
Labels: documentation, enhancement, size/XS

#43 Patch 1
  .github/CONTRIBUTING.md
  README.md
Labels: size/XS

#45 add Kevin Powell's youtube channel
  README.md
Labels: size/XS

#47 docs: add Dave Gray
  README.md
Labels: size/XS

#48 Added more youtubers
  README.md
Labels: size/XS

#50 Resources for DSA have been added
  DSA/README.md
Labels: size/XS

#51 Fixed Typos that were causing issues
  DSA/README.md
Labels: size/XS

#46 These channels helped me to level up my Front End Skills
  README.md
Labels: size/S
